const express = require('express')
const router = express.Router()
const { login, register, updateProfile } = require('../controller/userController')
const { protect } = require('../controller/authController')

router.post('/login', login)
router.post('/register', register)
router.patch('/update-profile', protect, updateProfile)
//router.patch('/add-favorite-product', () => { })
//router.get('/favorite-product', () => { })